-- 로그인 이력 테이블
USE app_db;

CREATE TABLE IF NOT EXISTS TB_LOGIN_LOG (
  LOG_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_ID VARCHAR(50) NOT NULL,
  LOGIN_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LOGIN_RESULT CHAR(1) NOT NULL, -- S: 성공, F: 실패
  IP_ADDR VARCHAR(50) NULL,
  REASON VARCHAR(200) NULL,
  CONSTRAINT fk_login_log_user
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  INDEX idx_login_log_user_dt (USER_ID, LOGIN_DT)
);


