-- 비밀번호 재설정 토큰 테이블
USE app_db;

CREATE TABLE IF NOT EXISTS TB_PWD_RESET (
  TOKEN CHAR(36) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR(50) NOT NULL,
  EXPIRES_AT DATETIME NOT NULL,
  USED TINYINT(1) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pwdreset_user FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  INDEX idx_pwdreset_user (USER_ID),
  INDEX idx_pwdreset_expires (EXPIRES_AT)
);


