-- 사용자 기본 정보 테이블
USE app_db;

CREATE TABLE IF NOT EXISTS TB_USER (
  USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
  USER_UUID CHAR(36) NOT NULL,
  USER_NM VARCHAR(100) NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  PASSWORD_SALT VARCHAR(255) NULL,
  PHONE_NO VARCHAR(20) NULL,
  EMAIL VARCHAR(100) NULL,
  ROLE_CD VARCHAR(20) NOT NULL DEFAULT 'USER',
  STATUS CHAR(1) NOT NULL DEFAULT 'A', -- A: 활성, I: 중지, L: 잠김
  LOGIN_FAIL_CNT INT NOT NULL DEFAULT 0,
  LAST_LOGIN_DT DATETIME NULL,
  PASSWORD_CHANGED_DT DATETIME NULL,
  CREATED_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(50) NULL,
  UPDATED_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50) NULL,
  UNIQUE KEY uq_tb_user_uuid (USER_UUID)
);


